2021-07-19 01:04:48,461 - api.py - INFO - started api on port 5000
2021-07-19 01:04:48,718 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 01:04:48,719 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:17:20,424 - api.py - INFO - started api on port 5000
2021-07-19 17:17:20,443 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:17:20,444 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:17:37,869 - controller.py - INFO - received /api/doctors get request with request form None
2021-07-19 17:17:37,869 - controller.py - INFO - returned /api/doctors get request with request form None
2021-07-19 17:17:37,875 - app - ERROR - Exception on /api/doctors [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'get_doctors' did not return a valid response. The function either returned None or ended without a return statement.
2021-07-19 17:17:37,879 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:17:37] "[35m[1mGET /api/doctors HTTP/1.1[0m" 500 -
2021-07-19 17:18:10,237 - api.py - INFO - started api on port 5000
2021-07-19 17:18:10,245 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:18:10,245 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:18:12,273 - controller.py - INFO - received /api/doctors get request with request form None
2021-07-19 17:18:12,274 - controller.py - INFO - returned /api/doctors get request with request form None
2021-07-19 17:18:12,275 - app - ERROR - Exception on /api/doctors [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'get_doctors' did not return a valid response. The function either returned None or ended without a return statement.
2021-07-19 17:18:12,276 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:18:12] "[35m[1mGET /api/doctors HTTP/1.1[0m" 500 -
2021-07-19 17:20:24,812 - api.py - INFO - started api on port 5000
2021-07-19 17:20:24,836 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:20:24,836 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:20:26,760 - controller.py - INFO - received /api/doctors get request with request form None
2021-07-19 17:20:26,760 - controller.py - INFO - returned /api/doctors get request with request form None
2021-07-19 17:20:26,760 - app - ERROR - Exception on /api/doctors [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'get_doctors' did not return a valid response. The function either returned None or ended without a return statement.
2021-07-19 17:20:26,762 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:20:26] "[35m[1mGET /api/doctors HTTP/1.1[0m" 500 -
2021-07-19 17:20:55,123 - api.py - INFO - started api on port 5000
2021-07-19 17:20:55,131 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:20:55,132 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:20:57,136 - controller.py - INFO - received /api/doctors get request with request form None
2021-07-19 17:20:57,136 - controller.py - INFO - returned /api/doctors get request with request form None
2021-07-19 17:20:57,137 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:20:57] "GET /api/doctors HTTP/1.1" 200 -
2021-07-19 17:36:38,634 - controller.py - INFO - received /api/doctors get request with request form None
2021-07-19 17:36:38,636 - controller.py - INFO - returned /api/doctors get request with request form None
2021-07-19 17:36:38,640 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:36:38] "GET /api/doctors HTTP/1.1" 200 -
2021-07-19 17:36:40,465 - api.py - INFO - started api on port 5000
2021-07-19 17:36:40,492 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:36:40,493 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:36:43,147 - controller.py - INFO - received /api/doctors get request with request form None
2021-07-19 17:36:43,148 - controller.py - INFO - returned /api/doctors get request with request form None
2021-07-19 17:36:43,149 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:36:43] "GET /api/doctors HTTP/1.1" 200 -
2021-07-19 17:37:51,515 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:37:51] "[31m[1mPOST /api/doctors HTTP/1.1[0m" 405 -
2021-07-19 17:38:01,577 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:38:01] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 405 -
2021-07-19 17:38:04,731 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:38:04] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 405 -
2021-07-19 17:38:16,808 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:38:16] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 405 -
2021-07-19 17:38:21,893 - api.py - INFO - started api on port 5000
2021-07-19 17:38:21,904 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:38:21,904 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:38:23,858 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:38:23] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 422 -
2021-07-19 17:40:08,991 - api.py - INFO - started api on port 5000
2021-07-19 17:40:09,015 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:40:09,016 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:40:10,736 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:40:10] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 422 -
2021-07-19 17:41:03,485 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:41:03] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 422 -
2021-07-19 17:41:08,996 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:41:08] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 422 -
2021-07-19 17:41:13,890 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:41:13] "POST /api/book-appointment HTTP/1.1" 200 -
2021-07-19 17:46:36,440 - api.py - INFO - started api on port 5000
2021-07-19 17:46:36,462 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:46:36,462 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:46:42,871 - app - ERROR - Exception on /api/book-appointment [POST]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 17, in book_appointment
    return controller.book_appointment()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 45, in book_appointment
    time_object = datetime.fromtimestamp(time)
TypeError: an integer is required (got type str)
2021-07-19 17:46:42,874 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:46:42] "[35m[1mPOST /api/book-appointment HTTP/1.1[0m" 500 -
2021-07-19 17:46:59,071 - app - ERROR - Exception on /api/book-appointment [POST]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 17, in book_appointment
    return controller.book_appointment()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 45, in book_appointment
    time_object = datetime.fromtimestamp(time)
TypeError: an integer is required (got type str)
2021-07-19 17:46:59,072 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:46:59] "[35m[1mPOST /api/book-appointment HTTP/1.1[0m" 500 -
2021-07-19 17:47:30,741 - api.py - INFO - started api on port 5000
2021-07-19 17:47:30,763 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:47:30,763 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:47:32,564 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:47:32] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 422 -
2021-07-19 17:47:39,637 - app - ERROR - Exception on /api/book-appointment [POST]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 17, in book_appointment
    return controller.book_appointment()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 45, in book_appointment
    time_object = datetime.fromtimestamp(float(time))
ValueError: could not convert string to float: 's'
2021-07-19 17:47:39,641 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:47:39] "[35m[1mPOST /api/book-appointment HTTP/1.1[0m" 500 -
2021-07-19 17:47:42,040 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:47:42] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 422 -
2021-07-19 17:48:07,808 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:48:07] "POST /api/book-appointment HTTP/1.1" 200 -
2021-07-19 17:53:18,621 - api.py - INFO - started api on port 5000
2021-07-19 17:53:18,636 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:53:18,636 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:53:41,302 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:53:41] "[31m[1mPOST /api/delete-appointment HTTP/1.1[0m" 405 -
2021-07-19 17:53:47,168 - app - ERROR - Exception on /api/delete-appointment [DELETE]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1727, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
2021-07-19 17:53:47,171 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:53:47] "[35m[1mDELETE /api/delete-appointment HTTP/1.1[0m" 500 -
2021-07-19 17:54:37,854 - api.py - INFO - started api on port 5000
2021-07-19 17:54:37,875 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:54:37,875 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:54:39,705 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:39] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 17:54:42,632 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:42] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 17:54:43,583 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:43] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 17:54:44,524 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:44] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 17:54:45,316 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:45] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 17:54:48,100 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:48] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 17:54:49,049 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:49] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 17:54:49,483 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:49] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 17:54:52,988 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:52] "[35m[1mDELETE /api/delete-appointment HTTP/1.1[0m" 204 -
2021-07-19 17:54:56,772 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:54:56] "[35m[1mDELETE /api/delete-appointment HTTP/1.1[0m" 204 -
2021-07-19 17:55:03,894 - api.py - INFO - started api on port 5000
2021-07-19 17:55:03,903 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 17:55:03,903 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 17:55:06,884 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:55:06] "[35m[1mDELETE /api/delete-appointment HTTP/1.1[0m" 204 -
2021-07-19 17:55:07,742 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 17:55:07] "[35m[1mDELETE /api/delete-appointment HTTP/1.1[0m" 204 -
2021-07-19 18:00:17,133 - api.py - INFO - started api on port 5000
2021-07-19 18:00:17,157 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:00:17,158 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:00:18,998 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:00:18] "[35m[1mDELETE /api/delete-appointment HTTP/1.1[0m" 204 -
2021-07-19 18:00:40,585 - api.py - INFO - started api on port 5000
2021-07-19 18:00:40,594 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:00:40,594 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:00:42,396 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:00:42] "[35m[1mDELETE /api/delete-appointment HTTP/1.1[0m" 204 -
2021-07-19 18:01:19,159 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:01:19] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 18:01:20,994 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:01:20] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 18:01:43,069 - api.py - INFO - started api on port 5000
2021-07-19 18:01:43,092 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:01:43,092 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:01:45,254 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:01:45] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 18:01:45,979 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:01:45] "[35m[1mDELETE /api/delete-appointment HTTP/1.1[0m" 204 -
2021-07-19 18:02:06,115 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:02:06] "POST /api/book-appointment HTTP/1.1" 200 -
2021-07-19 18:02:30,528 - api.py - INFO - started api on port 5000
2021-07-19 18:02:30,536 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:02:30,536 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:02:32,234 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:02:32] "POST /api/book-appointment HTTP/1.1" 200 -
2021-07-19 18:03:11,869 - api.py - INFO - started api on port 5000
2021-07-19 18:03:11,887 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:03:11,887 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:03:18,658 - app - ERROR - Exception on /api/book-appointment [POST]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 22, in book_appointment
    return controller.book_appointment()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 78, in book_appointment
    update_appointments_data(appointments)
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 28, in update_appointments_data
    json.dump(appointments, f)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UUID is not JSON serializable
2021-07-19 18:03:18,664 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:03:18] "[35m[1mPOST /api/book-appointment HTTP/1.1[0m" 500 -
2021-07-19 18:03:55,980 - app - ERROR - Exception on /api/book-appointment [POST]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 22, in book_appointment
    return controller.book_appointment()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 76, in book_appointment
    appointments = load_appointments_data()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 18, in load_appointments_data
    return json.load(open('./appointments.json', ))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 19 column 10 (char 329)
2021-07-19 18:03:55,983 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:03:55] "[35m[1mPOST /api/book-appointment HTTP/1.1[0m" 500 -
2021-07-19 18:04:21,893 - api.py - INFO - started api on port 5000
2021-07-19 18:04:21,902 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:04:21,902 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:04:23,976 - app - ERROR - Exception on /api/book-appointment [POST]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 22, in book_appointment
    return controller.book_appointment()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 76, in book_appointment
    appointments = load_appointments_data()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 18, in load_appointments_data
    return json.load(open('./appointments.json', ))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 19 column 10 (char 329)
2021-07-19 18:04:23,979 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:04:23] "[35m[1mPOST /api/book-appointment HTTP/1.1[0m" 500 -
2021-07-19 18:04:35,300 - app - ERROR - Exception on /api/book-appointment [POST]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 22, in book_appointment
    return controller.book_appointment()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 78, in book_appointment
    update_appointments_data(jsonify(appointments))
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 28, in update_appointments_data
    json.dump(appointments, f)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2021-07-19 18:04:35,303 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:04:35] "[35m[1mPOST /api/book-appointment HTTP/1.1[0m" 500 -
2021-07-19 18:05:04,601 - api.py - INFO - started api on port 5000
2021-07-19 18:05:04,623 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:05:04,623 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:05:07,128 - app - ERROR - Exception on /api/book-appointment [POST]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 22, in book_appointment
    return controller.book_appointment()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 78, in book_appointment
    update_appointments_data(appointments)
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 28, in update_appointments_data
    json.dump(appointments, f)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UUID is not JSON serializable
2021-07-19 18:05:07,133 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:05:07] "[35m[1mPOST /api/book-appointment HTTP/1.1[0m" 500 -
2021-07-19 18:05:53,636 - api.py - INFO - started api on port 5000
2021-07-19 18:05:53,645 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:05:53,645 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:05:55,605 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:05:55] "POST /api/book-appointment HTTP/1.1" 200 -
2021-07-19 18:13:52,867 - app - ERROR - Exception on /api/doctors [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 12, in get_doctors
    return controller.get_doctors()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 32, in get_doctors
    logger.info('received /api/doctors get request with request form {}'.format(j))
NameError: name 'j' is not defined
2021-07-19 18:13:52,879 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:13:52] "[35m[1mGET /api/doctors HTTP/1.1[0m" 500 -
2021-07-19 18:14:14,410 - api.py - INFO - started api on port 5000
2021-07-19 18:14:14,440 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:14:14,440 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:14:16,403 - app - ERROR - Exception on /api/doctors [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 12, in get_doctors
    return controller.get_doctors()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 32, in get_doctors
    logger.info('received /api/doctors get request with request form {}'.format(j))
NameError: name 'j' is not defined
2021-07-19 18:14:16,405 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:14:16] "[35m[1mGET /api/doctors HTTP/1.1[0m" 500 -
2021-07-19 18:14:29,828 - api.py - INFO - started api on port 5000
2021-07-19 18:14:29,836 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:14:29,836 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:14:31,710 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:14:31] "GET /api/doctors HTTP/1.1" 200 -
2021-07-19 18:14:43,562 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:14:43] "POST /api/book-appointment HTTP/1.1" 200 -
2021-07-19 18:15:26,148 - app - ERROR - Exception on /api/appointments [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 17, in get_appointments
    return controller.get_appointments()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 51, in get_appointments
    curr_appointment_date = datetime.fromtimestamp(float(appointment['time'])).date()
ValueError: could not convert string to float: 't'
2021-07-19 18:15:26,158 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:15:26] "[35m[1mGET /api/appointments?doctor%20id=0&time=1626729300 HTTP/1.1[0m" 500 -
2021-07-19 18:16:08,483 - api.py - INFO - started api on port 5000
2021-07-19 18:16:08,505 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:16:08,505 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:16:10,149 - app - ERROR - Exception on /api/appointments [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 17, in get_appointments
    return controller.get_appointments()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 53, in get_appointments
    curr_appointment_date = datetime.fromtimestamp(float(appointment['time'])).date()
ValueError: could not convert string to float: 't'
2021-07-19 18:16:10,152 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:16:10] "[35m[1mGET /api/appointments?doctor%20id=0&time=1626729300 HTTP/1.1[0m" 500 -
2021-07-19 18:16:45,433 - app - ERROR - Exception on /api/appointments [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yulizhi/Downloads/notable-health/backend/app.py", line 17, in get_appointments
    return controller.get_appointments()
  File "/Users/yulizhi/Downloads/notable-health/backend/controller.py", line 53, in get_appointments
    result_appointments.append(appointment)
ValueError: year 53516 is out of range
2021-07-19 18:16:45,436 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:16:45] "[35m[1mGET /api/appointments?doctor%20id=0&time=1626729300 HTTP/1.1[0m" 500 -
2021-07-19 18:17:10,975 - api.py - INFO - started api on port 5000
2021-07-19 18:17:10,984 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:17:10,984 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:17:12,607 - app - ERROR - Exception on /api/appointments [GET]
Traceback (most recent call last):
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/Users/yulizhi/Downloads/notable-health/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1727, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2021-07-19 18:17:12,612 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:17:12] "[35m[1mGET /api/appointments?doctor%20id=0&time=1626729300 HTTP/1.1[0m" 500 -
2021-07-19 18:18:03,100 - api.py - INFO - started api on port 5000
2021-07-19 18:18:03,121 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-19 18:18:03,122 - werkzeug - INFO -  * Running on http://192.168.2.11:5000/ (Press CTRL+C to quit)
2021-07-19 18:18:04,739 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:18:04] "GET /api/appointments?doctor%20id=0&time=1626729300 HTTP/1.1" 200 -
2021-07-19 18:19:11,928 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:19:11] "DELETE /api/delete-appointment HTTP/1.1" 200 -
2021-07-19 18:19:17,224 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:19:17] "GET /api/appointments?doctor%20id=0&time=1626729300 HTTP/1.1" 200 -
2021-07-19 18:19:50,725 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:19:50] "[31m[1mPOST /api/book-appointment HTTP/1.1[0m" 422 -
2021-07-19 18:20:14,780 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:20:14] "POST /api/book-appointment HTTP/1.1" 200 -
2021-07-19 18:20:30,469 - werkzeug - INFO - 127.0.0.1 - - [19/Jul/2021 18:20:30] "POST /api/book-appointment HTTP/1.1" 200 -
